@startuml
skinparam linetype ortho

entity Project {
  * uuid: UUID <<unique>>
  --
  * name: str
}

entity Operation {
  * uuid: UUID <<unique>>
  --
  * complated: bool
}

entity Service {
  * uuid: UUID <<unique>>
  --
  * name: str
  --
  * project: Project
}

entity Api {
  * uuid: UUID <<unique>>
  --
  * name: str
  --
  * plan: str
  --
  * service: Service
  --
  * basePath: str
  --
  * backend: Backend
}

entity Backend {
  * uuid: UUID <<unique>>
  --
  * name: str
  --
  * service: Service
  --
  * isPrivate: bool
}

entity Product {
  * uuid: UUID <<unique>>
  --
  * name: str
  --
  * apis: List[API]
}

entity IAM {
  * uuid: UUID <<unique>>
  --
  * name: str = "iam"
  --
  * project: Project
  --
  * users: List[User.UUID]
  --
  * groups: List[Group.UUID]
  --
  * groups: List[Role.UUID]
}

entity Role {
  * uuid: UUID <<unique>>
  --
  * name: str
}

entity Permission {
  * uuid: UUID <<unique>>
  --
  * name: str
  example: service.resource.method
  --
  * serviceId: Service.UUID
  --
  * resourceId: Resource.UUID
  --
  * method: str
}

entity Group {
  * uuid: UUID <<unique>>
  --
  * name: str
}

entity User {
  * uuid: UUID <<unique>>
  --
  * name: str
}

Project ||--|{ Service
Project ||--|| IAM
Project ||--|| Operation

Service ||--|{ Api
Service ||--|{ Backend
Service ||--|{ Product

Product }|--|{ Api
Api ||--|{ Backend

IAM ||--|{ Role
IAM ||--o{ Group
IAM ||--|{ User
Role }|--|{ Permission
Role }|--|{ Group
Role }|--|{ User
Group }|--|{ User

@enduml