@startuml
skinparam linetype ortho

entity Project {
  * uuid: UUID <<unique>>
  --
  * name: str
  --
  * services: List[ServiceSubset]
}

entity ServiceSubset {
  * uuid: UUID <<unique>>
  --
  * name: str
}

entity Service {
  * uuid: UUID <<unique>>
  --
  * name: str
}

entity Api {
  * uuid: UUID <<unique>>
  --
  * name: str
}

entity IAM {
  * uuid: UUID <<unique>>
  --
  * name: str = "iam"
  --
  * users: List[User.UUID]
  --
  * groups: List[Group.UUID]
  --
  * groups: List[Role.UUID]
}

entity Role {
  * uuid: UUID <<unique>>
  --
  * name: str
}

entity Permission {
  * uuid: UUID <<unique>>
  --
  * name: str
  example: service.resource.method
  --
  * serviceId: Service.UUID
  --
  * resourceId: Resource.UUID
  --
  * method: str
}

entity Group {
  * uuid: UUID <<unique>>
  --
  * name: str
}

entity User {
  * uuid: UUID <<unique>>
  --
  * name: str
}

Project ||--|{ Service
Project ||--|| IAM

Service ||--|{ Api

IAM ||--|{ Role
IAM ||--o{ Group
IAM ||--|{ User
Role }|--|{ Permission

@enduml